export default [
  {
    _id: '5c52de4c0f4ed2ae1bff8739',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Webster Burgess',
    star: 'EQUITOX',
  },
  {
    _id: '5c52de4cac35a17d8c0993c1',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Medina Glenn',
    star: 'CYCLONICA',
  },
  {
    _id: '5c52de4c54f2cb9b2eaca28e',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Ernestine Reyes',
    star: 'YURTURE',
  },
  {
    _id: '5c52de4c27a7eaf7b64d44ca',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Patrica Hess',
    star: 'MENBRAIN',
  },
  {
    _id: '5c52de4c470775a1e4041379',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Lawrence Sherman',
    star: 'SCENTRIC',
  },
  {
    _id: '5c52de4c491139efcc4d75cf',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Tessa Erickson',
    star: 'AUSTECH',
  },
  {
    _id: '5c52de4cb83143009752997c',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Crystal Doyle',
    star: 'ZILCH',
  },
  {
    _id: '5c52de4c4e4ae4ea190a4743',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Reyna Bradley',
    star: 'CUIZINE',
  },
  {
    _id: '5c52de4c916c0ec176cc25ab',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Estelle Gallagher',
    star: 'INTERODEO',
  },
  {
    _id: '5c52de4cf9da515d14735190',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Hendrix Rojas',
    star: 'MAKINGWAY',
  },
  {
    _id: '5c52de4c42ef39a57f1bd1ee',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Kimberly Nieves',
    star: 'XERONK',
  },
  {
    _id: '5c52de4cfdf070b1c0f5ed34',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Felecia Mcleod',
    star: 'LIMAGE',
  },
  {
    _id: '5c52de4c157415a10ad2f39e',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Enid Blankenship',
    star: 'ECLIPTO',
  },
  {
    _id: '5c52de4c94f0146ee1da0a39',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Rhodes Blanchard',
    star: 'HAIRPORT',
  },
  {
    _id: '5c52de4ccae10cfc264ea5e0',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Craig Woodard',
    star: 'KAGE',
  },
  {
    _id: '5c52de4c47d12f28075e233b',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Mathews Clements',
    star: 'HALAP',
  },
  {
    _id: '5c52de4c277356ce5898add2',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Patti Burke',
    star: 'MAGNEATO',
  },
  {
    _id: '5c52de4c3da0e66a28848c49',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Catalina Thompson',
    star: 'AFFLUEX',
  },
  {
    _id: '5c52de4cdc5398d1d0e2e613',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Soto Dale',
    star: 'POSHOME',
  },
  {
    _id: '5c52de4c281e927761f597d8',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Downs Williams',
    star: 'HANDSHAKE',
  },
  {
    _id: '5c52de4ca2eba72ff8b19bbf',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Townsend Mckee',
    star: 'UNIWORLD',
  },
  {
    _id: '5c52de4c8abcc5cfdf8a62f7',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Washington Serrano',
    star: 'ZUVY',
  },
  {
    _id: '5c52de4cd45a1e52209e3d35',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Georgia Dixon',
    star: 'PEARLESSA',
  },
  {
    _id: '5c52de4ca30e999fd297f483',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Mona Parker',
    star: 'INSURITY',
  },
  {
    _id: '5c52de4c135e3122a92916e4',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Slater Brewer',
    star: 'VORTEXACO',
  },
  {
    _id: '5c52de4c09d3e98855c67981',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Reilly Barron',
    star: 'ANDERSHUN',
  },
  {
    _id: '5c52de4c43f2985efaca8ca8',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Doreen Cummings',
    star: 'CODAX',
  },
  {
    _id: '5c52de4c188e45c9d2bcb429',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Hood Flores',
    star: 'ORGANICA',
  },
  {
    _id: '5c52de4c5ede5c3037c54a39',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Pansy Tucker',
    star: 'SHOPABOUT',
  },
  {
    _id: '5c52de4c0a312078fdf62dc9',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Joanne Phillips',
    star: 'CIRCUM',
  },
  {
    _id: '5c52de4c28d9507099a79f85',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Duncan Roberson',
    star: 'EPLOSION',
  },
  {
    _id: '5c52de4c5717df3361de5d9e',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Kemp Ward',
    star: 'XINWARE',
  },
  {
    _id: '5c52de4cbf590fd683fde1f3',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Scott Peterson',
    star: 'GEOFORMA',
  },
  {
    _id: '5c52de4c853220c9458f9f34',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Adriana Carter',
    star: 'COMTRACT',
  },
  {
    _id: '5c52de4c2b503a2e56f755aa',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Fannie Travis',
    star: 'TELEPARK',
  },
  {
    _id: '5c52de4c8fca3d8a5f821c1d',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Josefa Atkinson',
    star: 'VIAGRAND',
  },
  {
    _id: '5c52de4c620f75877df84b90',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Rosalind Ford',
    star: 'EURON',
  },
  {
    _id: '5c52de4c953b4bec45f8d0db',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Melton Valdez',
    star: 'HOMELUX',
  },
  {
    _id: '5c52de4cc731db814480c166',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Whitaker Weeks',
    star: 'TELPOD',
  },
  {
    _id: '5c52de4cc90d14bc6c4ffe3b',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Della Brady',
    star: 'SYNTAC',
  },
  {
    _id: '5c52de4cb60cf682a8db9f87',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Lynch Winters',
    star: 'VICON',
  },
  {
    _id: '5c52de4cf7066656d5d162a6',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Margaret Day',
    star: 'SIGNITY',
  },
  {
    _id: '5c52de4ca51bb600c6579963',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Fischer Bush',
    star: 'DUOFLEX',
  },
  {
    _id: '5c52de4ca0ae72e0a293a294',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Aileen Greer',
    star: 'EYERIS',
  },
  {
    _id: '5c52de4c7f102459b57142b3',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Yesenia Walsh',
    star: 'ECLIPSENT',
  },
  {
    _id: '5c52de4c970f2a6247995343',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Summers Herman',
    star: 'MAGNINA',
  },
  {
    _id: '5c52de4c25048abc1d13e86d',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Mcneil Cooke',
    star: 'COMTREK',
  },
  {
    _id: '5c52de4c4211b38a38eaac2b',
    picture: 'https://ui-avatars.com/api/?background=0D8ABC&color=fff',
    name: 'Newman Franklin',
    star: 'FORTEAN',
  },
];
